# Generated by Django 5.2.4 on 2025-09-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lean_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='payments.leancustomer')),
            ],
        ),
    ]
