# Generated by Django 5.2.4 on 2025-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_leanentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='gold_invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='balance',
            name='silver_invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
