# Generated by Django 5.2.4 on 2025-09-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='goal_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total target amount (investment + growth)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('goal', 'Goal-based')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('lease_payout', 'Lease Payout')], max_length=16),
        ),
    ]
