# Generated by Django 5.2.4 on 2025-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_sipplan_end_date_sipplan_goal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('gold_purchase', 'Gold Purchase'), ('gold_sellout', 'Gold Sellout'), ('silver_purchase', 'Silver Purchase'), ('silver_sellout', 'Silver Sellout'), ('lease_payout', 'Lease Payout'), ('lease_creation', 'Lease Creation'), ('refund', 'Refund')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=16),
        ),
    ]
