# Generated by Django 5.2.4 on 2025-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_wallettransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='leased_gold_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
