# Generated by Django 5.2.4 on 2025-09-28 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_balance_leased_gold_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(condition=models.Q(('leased_gold_quantity__lte', models.F('gold_quantity'))), name='leased_gold_lte_gold_quantity'),
        ),
    ]
