# Generated by Django 5.2.4 on 2025-10-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_balance_leased_gold_lte_gold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='sip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.sipplan'),
        ),
    ]
