# Generated by Django 5.2.4 on 2025-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_margin', models.IntegerField(default=0, verbose_name='Gold Margin (%)')),
                ('silver_margin', models.IntegerField(default=0, verbose_name='Silver Margin (%)')),
                ('gold_appreciation', models.IntegerField(default=0, verbose_name='Gold Appreciation (%)')),
                ('silver_appreciation', models.IntegerField(default=0, verbose_name='Silver Appreciation (%)')),
            ],
        ),
    ]
