# Generated by Django 5.2.4 on 2025-08-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformoptions',
            options={'verbose_name': 'Platform Options', 'verbose_name_plural': 'Platform Options'},
        ),
    ]
