# Generated by Django 5.2.4 on 2025-08-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_alter_platformoptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformoptions',
            options={},
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
