# Generated by Django 5.2.4 on 2025-08-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_alter_platformoptions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformoptions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
