# Generated by Django 5.2.4 on 2025-08-11 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_alter_platformoptions_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('asset_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('transaction_id', models.CharField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=100)),
                ('quantity_owned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_purchased_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_sold_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset_type')},
            },
        ),
    ]
