# Generated by Django 5.2.4 on 2025-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_assettransaction_assetledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='margin',
            field=models.IntegerField(default=0.8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='gold_appreciation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Gold Appreciation (%)'),
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='gold_margin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Gold Margin (%)'),
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='silver_appreciation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Silver Appreciation (%)'),
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='silver_margin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Silver Margin (%)'),
        ),
    ]
