# Generated by Django 5.2.4 on 2025-09-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0008_pushtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssetLedger',
        ),
        migrations.DeleteModel(
            name='AssetTransaction',
        ),
    ]
