# Generated by Django 5.2.4 on 2025-09-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0009_remove_assettransaction_user_delete_assetledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='expo_push_token',
        ),
    ]
