# Generated by Django 5.2.4 on 2025-09-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0011_goldlease_leasepayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldlease',
            old_name='quantity_grams',
            new_name='quantity',
        ),
    ]
