# Generated by Django 5.2.4 on 2025-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0012_rename_quantity_grams_goldlease_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldlease',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
