# Generated by Django 5.2.4 on 2025-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0013_goldlease_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldlease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
