# Generated by Django 5.2.4 on 2025-10-15 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0014_goldlease_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricealert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_triggered', False)), fields=('user', 'asset', 'condition', 'target_price'), name='unique_active_price_alert'),
        ),
    ]
