# Generated by Django 5.2.4 on 2025-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0015_pricealert_unique_active_price_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoptions',
            name='gold_markdown',
            field=models.DecimalField(decimal_places=3, default=1.7, max_digits=10, verbose_name='Gold Markdown (%)'),
        ),
        migrations.AddField(
            model_name='platformoptions',
            name='silver_markdown',
            field=models.DecimalField(decimal_places=3, default=1.7, max_digits=10, verbose_name='Silver Markdown (%)'),
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='gold_margin',
            field=models.DecimalField(decimal_places=3, default=1.2, max_digits=10, verbose_name='Gold Margin (%)'),
        ),
        migrations.AlterField(
            model_name='platformoptions',
            name='silver_margin',
            field=models.DecimalField(decimal_places=3, default=1.2, max_digits=10, verbose_name='Silver Margin (%)'),
        ),
    ]
