# Generated by Django 5.2.4 on 2025-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal_type',
            field=models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Platinum', 'platinum'), ('Diamond', 'diamond')], default='gold', max_length=50),
        ),
    ]
