# Generated by Django 5.2.4 on 2025-09-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('review', 'Under Review')], default='pending', max_length=20),
        ),
    ]
