# Generated by Django 5.2.4 on 2025-10-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
